# Indique à l'application de sauvegarder dans un fichier local sur ton Mac
spring.datasource.url=jdbc:h2:file:./data/friendconnectdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permet à Hibernate de créer les tables automatiquement sur le disque
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true